Include linting as part of the CI build pipeline.
stactools-packages/sentinel1 pull request #20
Opened 2022-12-20 02:51 UTC by sharkinsspatial

Before you submit a pull request, please fill in the following:

**Related Issue(s):**
None

**Description:**
Currently,  the `cibuild` script does not call `./scripts/lint`.   As a consequence, commits have been introduced that cause `main` to fail `mypy` checks.  Rather than relying on the recommendation that committers manually run `./scripts/lint` on their local repository, this PR includes linting as part of the CI pipeline and fixes the existing `mypy` errors. 

**PR checklist:**

- [x] Code is formatted (run `scripts/format`).
- [x] Code lints properly (run `scripts/lint`).
- [x] Tests pass (run `scripts/test`).
- [x] Documentation has been updated to reflect changes, if applicable.
- [ ] Changes are added to the [CHANGELOG](../CHANGELOG.md).

2023-01-11 12:11 UTC, gadomski requested changes
It's not required, but the stactools-packages "best practices" (as codified in https://github.com/stactools-packages/template) have been updated since this repo was created. There's a couple of PRs out there "modernizing" older stactools-packages if you want to use them as a spirit guide:
- https://github.com/stactools-packages/goes/pull/26
- https://github.com/stactools-packages/aster/pull/8
- https://github.com/stactools-packages/landsat/pull/40
- https://github.com/stactools-packages/threedep/pull/11

Should mostly be a matter of adding pre-commit and tweaking those test scripts a bit.

2023-01-11 12:11 UTC, gadomski commented on scripts/cibuild
> +        ./scripts/lint
Not needed, `./scripts/lint` is called from `./scripts/test`: https://github.com/stactools-packages/sentinel1/blob/e27e50bac8050fa5613e282e3350578fc0d35fe7/scripts/test#L20

2023-01-12 19:28 UTC, sharkinsspatial commented
@gadomski We have a follow on PR to implement the modernized template https://github.com/sharkinsspatial/sentinel1/pull/1 that we will submit shortly as well.

2023-01-12 19:34 UTC, gadomski approved these changes

2023-01-12 20:26 UTC, merged