add projection extension metadata to GRD Items
stactools-packages/sentinel1 pull request #34
Opened 2023-03-29 18:28 UTC by philvarner

**Related Issue(s):**

n/a

**Description:**

**PR checklist:**

- [X] Code is formatted (run `scripts/format`).
- [X] Code lints properly (run `scripts/lint`).
- [X] Tests pass (run `scripts/test`).
- [X] Documentation has been updated to reflect changes, if applicable.
- [X] Examples have been updated to reflect changes, if applicable
- [X] Changes are added to the [CHANGELOG](../CHANGELOG.md).

2023-03-29 21:35 UTC, pjhartzell approved these changes

2023-03-29 23:47 UTC, pholleway approved these changes

2023-03-30 13:30 UTC, gadomski requested changes
Needs an `examples/` update?

2023-05-08 20:17 UTC, philvarner commented on .pre-commit-config.yaml
> +            args: ["--ignore", ".github/ISSUE_TEMPLATE/feature_request.md", "--disable", "MD024"]
disables duplicate header detection, so the README can have multiple subheadings named RTC and GRD.

2023-05-08 20:17 UTC, philvarner commented on README.md
> -- [Item (RTC)](examples/sentinel1-rtc-aws/2016/S1B_20161121_12SYJ_ASC/S1B_20161121_12SYJ_ASC.json)
this were all broken

2023-05-08 20:57 UTC, gadomski requested changes

2023-05-08 20:57 UTC, gadomski commented on CHANGELOG.md
> +>>>>>>> main
```suggestion
```

Leftover merge conflict marker.

2023-05-08 20:57 UTC, gadomski approved these changes

2023-05-09 12:35 UTC, merged